server:
  ssl:
    enabled: true
    key-store: classpath:.keystore
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store-password: '!q1w2e3r4t5'
    key-store-type: PKCS12
    # key-password: ''
    # key-alias: bns-ssl
  port: 8088

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/trello?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  sql:
#    init:
#      mode: always
#      platform: h2

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

